In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
#imports
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [3]:
#creating data to predict
data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]
print(data)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]


In [4]:
#function to split data
def splitData(seq, nSteps):
    
    #Declare x and y as empty list
    x = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + nSteps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #create input and output sequence
        seqX, seqY = seq[i:lastIndex], seq[lastIndex]
        
        #append seqX, seqY in x and y list
        x.append(seqX)
        y.append(seqY)
        pass
    #Convert x and y into numpy array
    x = np.array(x)
    y = np.array(y)
    
    return x,y 
    
    pass

In [5]:
#spliting data
nSteps = 5
x, y = splitData(data, nSteps = 5)

In [6]:
#printing x data
print(x)

[[ 10  20  30  40  50]
 [ 20  30  40  50  60]
 [ 30  40  50  60  70]
 [ 40  50  60  70  80]
 [ 50  60  70  80  90]
 [ 60  70  80  90 100]
 [ 70  80  90 100 110]
 [ 80  90 100 110 120]
 [ 90 100 110 120 130]
 [100 110 120 130 140]
 [110 120 130 140 150]
 [120 130 140 150 160]
 [130 140 150 160 170]
 [140 150 160 170 180]
 [150 160 170 180 190]]


In [7]:
#printing y data
print(y)

[ 60  70  80  90 100 110 120 130 140 150 160 170 180 190 200]


In [8]:
for i in range(len(x)):
    print(x[i], y[i])

[10 20 30 40 50] 60
[20 30 40 50 60] 70
[30 40 50 60 70] 80
[40 50 60 70 80] 90
[50 60 70 80 90] 100
[ 60  70  80  90 100] 110
[ 70  80  90 100 110] 120
[ 80  90 100 110 120] 130
[ 90 100 110 120 130] 140
[100 110 120 130 140] 150
[110 120 130 140 150] 160
[120 130 140 150 160] 170
[130 140 150 160 170] 180
[140 150 160 170 180] 190
[150 160 170 180 190] 200


In [9]:
#reshaping data
nFeatures = 1
x = x.reshape((x.shape[0], x.shape[1], nFeatures))
print(x[:2])

[[[10]
  [20]
  [30]
  [40]
  [50]]

 [[20]
  [30]
  [40]
  [50]
  [60]]]


In [10]:
#creating model
model = tf.keras.Sequential()
lrelu = lambda c: tf.keras.activations.relu(c, alpha=0.1)
model.add(layers.LSTM(50, activation=lrelu, input_shape=(nSteps, nFeatures)))
model.add(layers.Dense(1))
model.summary()

2022-12-17 00:30:25.719515: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 50)                10400     
_________________________________________________________________
dense (Dense)                (None, 1)                 51        
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [11]:
#compiling model
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [12]:
#training model
model.fit(x, y, epochs=200, verbose=1)

Epoch 1/200


2022-12-17 00:30:26.190168: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


1/1 [==============================] - 2s 2s/step - loss: 21580.2285 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 8ms/step - loss: 16159.5645 - accuracy: 0.0000e+00
Epoch 3/200
1/1 [==============================] - 0s 6ms/step - loss: 11894.4521 - accuracy: 0.0000e+00
Epoch 4/200
1/1 [==============================] - 0s 5ms/step - loss: 8743.1309 - accuracy: 0.0000e+00
Epoch 5/200
1/1 [==============================] - 0s 6ms/step - loss: 5966.7686 - accuracy: 0.0000e+00
Epoch 6/200
1/1 [==============================] - 0s 6ms/step - loss: 2917.4651 - accuracy: 0.0000e+00
Epoch 7/200
1/1 [==============================] - 0s 6ms/step - loss: 570.4940 - accuracy: 0.0000e+00
Epoch 8/200
1/1 [==============================] - 0s 7ms/step - loss: 1468.3937 - accuracy: 0.0000e+00
Epoch 9/200
1/1 [==============================] - 0s 6ms/step - loss: 1356.6313 - accuracy: 0.0000e+00
Epoch 10/200
1/1 [==============================] - 0s 6ms/step - loss: 798

In [13]:
#predicting
testData = np.array([90, 100, 110, 120, 130])
testData = testData.reshape((1, nSteps, nFeatures))
print(testData)

[[[ 90]
  [100]
  [110]
  [120]
  [130]]]


In [14]:
#result of predict
predictNextNumber = model.predict(testData, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 268ms/step
[[140.12766]]


In [15]:
#one more test
testData = np.array([160, 170, 180, 190, 200])
testData = testData.reshape((1, nSteps, nFeatures))
print(testData)

[[[160]
  [170]
  [180]
  [190]
  [200]]]


In [16]:
#result
predictNextNumber = model.predict(testData, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 26ms/step
[[211.0175]]
